### ISSUE TITLE
ToDo list video-maker

### ISSUE THREAD

**Issue by gomesgui06** [gomesgui06/video-maker#1]
- [x] Especificar tarefas e escopo

---

- [ ] **Orquestrador**
 - [x] Perguntar pelo termo de busca
 - [x] Perguntar pelo prefixo
 - [x] Iniciar robô de texto
 - [x] Iniciar robô de imagem
 - [x] Iniciar robô de vídeo
 - [ ] Iniciar robô de Youtube

---
 - [x] **Robô de texto**
 - [x] Estrutura de dados
 - [x] Pegar conteúdo da wikipedia
 - [x] Limpar o conteúdo
 - [x] Quebrar sentenças
 - [x] Pegar a interpretação do Watson
 - [x]  Adicionar tags
 - [x] Salvar a estrutura de dados

---
- [x]  **Robô de imagens**
 - [x] Carregar a estrutura de dados
 - [x] Buscar as imagens no Google imagens
 - [x] Baixar as imagens
 - [x] Salvar a estrutura de dados
---
 - [x] **Robô de vídeo**
 - [x] Preparar/redimensionar as imagens 
 - [x] Criar as sentenças com as imagens
 - [x] Criar o thumbnail para o vídeo
 - [x] Renderizar o vídeo com After Effects

---
 - [x] **Robô do youtube**
 - [x] Autenticar com OAuth
 - [x] Upload do vídeo
 - [x] Upload do thumbnail
